# Generated by Django 3.1.7 on 2021-03-19 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0002_auto_20210319_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('home_type', models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse')], default='House', max_length=50)),
                ('sqft', models.IntegerField()),
                ('open_house', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_one', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_two', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_three', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_four', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_five', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_six', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_seven', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_eight', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_nine', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_ten', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=15)),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('To Rent', 'To Rent')], default='For Sale', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
